# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
gravity <- function(nodes, strength, center, alpha) {
    .Call('imvisoned_gravity', PACKAGE = 'imvisoned', nodes, strength, center, alpha)
}

#' @export
homing2 <- function(start, current, threshold, strength, alpha) {
    .Call('imvisoned_homing2', PACKAGE = 'imvisoned', start, current, threshold, strength, alpha)
}

#' @export
nonoverlap <- function(nodes, radii) {
    .Call('imvisoned_nonoverlap', PACKAGE = 'imvisoned', nodes, radii)
}

#' @export
perturbate <- function(nodes, tol = 1e-6) {
    .Call('imvisoned_perturbate', PACKAGE = 'imvisoned', nodes, tol)
}

#' @export
repluse <- function(nodes, charge, thresh, alpha) {
    .Call('imvisoned_repluse', PACKAGE = 'imvisoned', nodes, charge, thresh, alpha)
}

#' @export
repulse2 <- function(nodes, charge, weight, alpha) {
    .Call('imvisoned_repulse2', PACKAGE = 'imvisoned', nodes, charge, weight, alpha)
}

